site_name: Image+
docs_dir: docs
site_dir: _build/site
edit_uri: tree/master/docs

repo_name: 'Jako/ImagePlus'
repo_url: https://github.com/Jako/ImagePlus

copyright: '&copy; 2015-2023 <a href="https://treehillstudio.com">Treehill Studio</a>'

nav:
- Description: 'index.md'
- Installation: 'installation.md'
- Getting Started: 'getting-started.md'
- Usage: 'usage.md'
- Examples: 'examples.md'
- Contributors: 'contributors.md'

extra:
  analytics:
    provider: matomo
    url: matomo.treehillstudio.com
    site: 40
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Jako

theme:
  name: material
  custom_dir: ../../mkdocs-material-treehillstudio/material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: false
  font: false

markdown_extensions:
  - footnotes
  - tables
  - admonition
  - meta
  - toc
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - glightbox
  - search
